### ISSUE TITLE
Clarify markdown levels for nbpages

### ISSUE THREAD

**Issue by mquevill** [ndcbe/cbe67701-uncertainty-quantification#10]
In the cell about markdown levels, there's a disconnect between standard markdown levels and `nbpages` levels. Perhaps additional clarification about these might be helpful. For instance: In `nbpages` "title" will be 1.1, "section" will be 1.1.1, "subsection" will be 1.1.1.1, etc. but a markdown user might expect "title" to be 1, "section" to be 1.1, etc.

**nbpages:** (if we are _inside_ example 1)
```
1.1 title
    1.1.1 section
        1.1.1.1 subsection
            ...
```
**markdown:**
```
1 title
    1.1 section
        1.1.1 subsection
            ...
```

https://github.com/ndcbe/cbe67701-uncertainty-quantification/blob/e224cc6c4684c931c2214c376ee29b36388076aa/notebooks/01.01-Contributed-Example.ipynb#L57-L78

**Comment by adowling2** [comment]
Closed by #11.
